# File: .github/workflows/keep-alive.yml

name: Keep Render Instance Alive

# This workflow runs on a schedule
on:
  schedule:
    # Runs every 15 minutes, all the time.
    # This is a good frequency for keeping a free-tier instance warm.
    - cron: '*/15 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send keep-alive request to Render service
        run: curl -sS --fail "${{ https://parthbajaj.onrender.com/ }}"